"""Add a default value to the isActive column

Revision ID: 62f0aa4930e2
Revises: eb63a04bef4a
Create Date: 2025-05-17 17:05:10.935026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '62f0aa4930e2'
down_revision = 'eb63a04bef4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')


    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsActive', sa.Boolean(), nullable=True, default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('IsActive')


    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B613D13F6A9')
    )
    # ### end Alembic commands ###
