"""Add an IsActive column

Revision ID: eb63a04bef4a
Revises: 
Create Date: 2025-05-17 16:55:18.047132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'eb63a04bef4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('Users', schema=None) as batch_op:

        batch_op.add_column(sa.Column('IsActive', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('IsActive')

    # ### end Alembic commands ###
